tools:
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'tests/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'tests/*'
            paths: {  }
    php_analyzer:
        enabled: true
        config:
            metrics_coupling:
                enabled: true
                stable_code: { namespace_prefixes: {  }, classes: {  } }
            metrics_lack_of_cohesion_methods:
                enabled: true
            basic_semantic_checks:
                enabled: true
                property_on_interface: true
                missing_abstract_methods: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'tests/*'
            paths: {  }
        path_configs: {  }
    external_code_coverage:
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'tests/*'
            paths: {  }
filter:
    excluded_paths:
        - 'tests/*'
    paths: {  }
build_failure_conditions: {  }
